%(
	:auth<collection>,
	:authors(
		"finanalyst",
		"rawleyfowler"
	),
	:custom-raku<tm-blocks.raku>,
	:license<Artistic-2.0>,
	:name<tablemanager>,
	:render,
	:template-raku<tm-temps.raku>,
	:version<0.1.0>,
	:jquery<tableManager.js>,
	:add-css<
		tm-styling.css
		tm-light.css tm-dark.css
	>,
	:information<add-css>,
)