%(
	:add-css<all.min.css>,
	:jquery(['all.min.js',-1]),
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<font-awesome>,
	:render<fa-assets.raku>,
	:template-raku<fa-template.raku>,
	:version<0.4.3>,
	:information<jquery>,
)