#!/usr/bin/env bash
if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit
fi
echo Website/plugins/$1
if [ -d Website/plugins/$1/scss ];
then
    sass --update --no-source-map Website/plugins/$1/scss:Website/plugins/$1/css
else
    sass --update --no-source-map Website/plugins/$1:Website/plugins/$1
fi