%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:css<camelia-styling.css>,
	:custom-raku<camelia-blocks.raku>,
	:license<Artistic-2.0>,
	:name<camelia>,
	:render<move-images.raku>,
	:template-raku<camelia-templates.raku>,
	:version<0.3.1>,
)