agents:
  queue: raku-doc
steps:
  - label: "Build site"
    key: build
    commands:
      - ./.buildkite/setup-typegraphs-cache.sh
      - zef install . --deps-only
      - ./bin_files/build-site --without-completion --no-status
      - ./bin_files/build-site --no-status EBook
      - buildkite-agent artifact upload ./rendered_html/RakuDocumentation.epub
      - ./.buildkite/archive.sh
      - buildkite-agent artifact upload ./raku-doc-website.tar.gz
      - rm ./raku-doc-website.tar.gz

  - label: "Containerize static assets (tag: latest)"
    key: container
    if: build.branch == 'main'
    depends_on:
      - build
    commands:
      - buildkite-agent artifact download --step build raku-doc-website.tar.gz .
      - ./.buildkite/container.sh latest

  - label: "Containerize static assets (tag: docs-dev)"
    key: container-dev
    if: build.branch == 'docs-dev'
    depends_on:
      - build
    commands:
      - buildkite-agent artifact download --step build raku-doc-website.tar.gz .
      - ./.buildkite/container.sh docs-dev

