%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<typegraph>,
	:render<add-type-graph.raku>,
	:template-raku<tp-template.raku>,
	:add-css<typegraph-styling.css>,
	:version<0.2.2>,
)