%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:compilation<gen-secondaries.raku>,
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<secondaries>,
	:render<namespace-check.raku>,
	:template-raku<header-templates.raku>,
	:transfer<cleanup.raku>,
	:version<0.2.4>,
)