%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:css<image-styling.css>,
	:custom-raku<image-blocks.raku>,
	:license<Artistic-2.0>,
	:name<images>,
	:render<image-helper.raku>,
	:template-raku<image-templates.raku>,
	:transfer<image-collector.raku>,
	:version<0.3.1>,
)