%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:compilation<compilation-callable.raku>,
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<sqlite-db>,
	:render,
	:transfer<cleanup.raku>,
	:template-raku(),
	:version<0.1.0>,
	:database-dir<../sqlite-db>,
	:db-filename<sqlite-db.sql>,
)