%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:compilation<listf-collator.raku>,
	:css<listf-styling.css>,
	:custom-raku<listf-blocks.raku>,
	:license<Artistic-2.0>,
	:name<listfiles>,
	:render,
	:template-raku<listf-templates.raku>,
	:version<0.2.1>,
)