%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<git-reflog>,
	:render,
	:setup<add-ref-hash.raku>,
	:template-raku<reflog.raku>,
	:information<template-raku>,
	:version<0.1.0>,
)