%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:completion<completion-callable.raku>,
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<ebook-embed>,
	:render<move-files.raku>,
	:template-raku<ebook-styling.raku>,
	:transfer<transfer-callable.raku>,
	:version<0.1.3>,
	:ebook-path-name<ebook.epub>,
	:add-css<css/page.css>,
)