%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku<filter-blocks.raku>,
	:jquery<filter-script.js>,
	:license<Artistic-2.0>,
	:name<filterlines>,
	:render,
	:template-raku<filter-template.raku>,
	:version<0.2.0>,
)