name: Build Docker Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker container
      env:
        QUAY_USERNAME: ${{ secrets.REGISTRY_RW_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.REGISTRY_RW_PASSWORD }}
      run: ./scripts/cibuild-new-site.sh

